name: CI
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - "**"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: npm install
      - run: npm run test
      - run: cargo test
      - run: npm run generate
      - run: git diff --exit-code